{% set name = "mkdocstrings-python" %}
{% set version = "1.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bfb5e29acfc69c9177d2b11c18d3127d16e553b8da9bb6d184e428d54795600b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - pdm >2
    - pdm-backend
  run:
    - python >=3.8
    - mkdocstrings >=0.25
    - griffe >=0.48

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
