{% set name = "mkdocstrings-python" %}
{% set version = "1.16.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cdfc1a99fe5f6f0d90446a364ef7cac12014a4ef46114b2677a58cec84007117

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm >2
    - pdm-backend
  run:
    - python >={{ python_min }}
    - mkdocstrings >=0.28.3
    - griffe >=0.49
    - mkdocs-autorefs >=1.4
    - typing_extensions >=4.0

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
