{% set name = "mkdocstrings-python" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b72301fff739070ec517b5b36bf2f7c49d1360a275896a64efb97fc17d3f3968

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
    - pdm-pep517
  run:
    - python >=3.7
    - mkdocstrings >=0.20
    - griffe >=0.24

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocstrings-python/
  doc_url: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
