{% set name = "mkdocstrings-python" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 546d53c7d559941abc726b2f78a41c0183480a95ba0a87ccc63b9b08740126f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm >2
    - pdm-backend
  run:
    - python >={{ python_min }}
    - mkdocstrings >=0.28
    - griffe >=0.49
    - mkdocs-autorefs >=1.2
    - typing_extensions >=4.0

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
