{% set name = "mkdocstrings-python" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-python-{{ version }}.tar.gz
  sha256: e52bbfbf4c3ce9c3c8e692308b4154f9c9de0d7131a675e3c8844c3dad6283b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - python >=3.7
    - mkdocstrings >=0.18
    - griffe >=0.11.1

test:
  commands:
    - pip check
    - pytest tests.py
  requires:
    - pip
    - pytest
  files:
    - tests.py

about:
  home: https://pypi.org/project/mkdocstrings-python
  doc_url: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
